"""award dates

Revision ID: 057f3879a987
Revises: c456e8f8bce6
Create Date: 2020-07-24 15:29:56.690707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '057f3879a987'
down_revision = 'c456e8f8bce6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('award', sa.Column('end_date', sa.DateTime(), nullable=True))
    op.add_column('award', sa.Column('start_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('award', 'start_date')
    op.drop_column('award', 'end_date')
    # ### end Alembic commands ###
