"""Work History Table

Revision ID: 0d7cb57d907d
Revises: 01dcc82c3b3d
Create Date: 2020-07-24 13:36:58.009314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d7cb57d907d'
down_revision = '01dcc82c3b3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=140), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_history')
    # ### end Alembic commands ###
