"""duties table

Revision ID: 19cb14b95162
Revises: fa9292aa8da2
Create Date: 2020-07-27 14:24:49.805403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19cb14b95162'
down_revision = 'fa9292aa8da2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workhistory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=140), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('title_url', sa.String(length=120), nullable=True),
    sa.Column('supervisor', sa.String(length=60), nullable=True),
    sa.Column('supervisor_title', sa.String(length=60), nullable=True),
    sa.Column('supervisor_email', sa.String(length=120), nullable=True),
    sa.Column('supervisor_phone', sa.String(length=12), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('duty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['workhistory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('work_history')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_history',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('url', sa.VARCHAR(length=140), nullable=True),
    sa.Column('name', sa.VARCHAR(length=120), nullable=True),
    sa.Column('title', sa.VARCHAR(length=120), nullable=True),
    sa.Column('location', sa.VARCHAR(length=120), nullable=True),
    sa.Column('start_date', sa.DATETIME(), nullable=True),
    sa.Column('end_date', sa.DATETIME(), nullable=True),
    sa.Column('lat', sa.FLOAT(), nullable=True),
    sa.Column('lon', sa.FLOAT(), nullable=True),
    sa.Column('title_url', sa.VARCHAR(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('duty')
    op.drop_table('workhistory')
    # ### end Alembic commands ###
