"""add lat lon to WorkHistory

Revision ID: 9d543c9b12fb
Revises: 057f3879a987
Create Date: 2020-07-27 10:58:14.904726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d543c9b12fb'
down_revision = '057f3879a987'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_history', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('work_history', sa.Column('lon', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_history', 'lon')
    op.drop_column('work_history', 'lat')
    # ### end Alembic commands ###
