"""award license number

Revision ID: c456e8f8bce6
Revises: da2cf8cd5801
Create Date: 2020-07-24 14:51:20.978232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c456e8f8bce6'
down_revision = 'da2cf8cd5801'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('award', sa.Column('license_number', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('award', 'license_number')
    # ### end Alembic commands ###
