"""award table

Revision ID: da2cf8cd5801
Revises: 0d7cb57d907d
Create Date: 2020-07-24 14:47:29.981634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da2cf8cd5801'
down_revision = '0d7cb57d907d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('award',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=140), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('agency', sa.String(length=120), nullable=True),
    sa.Column('expiration_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('award')
    # ### end Alembic commands ###
