"""url building function in WorkHistory

Revision ID: fa9292aa8da2
Revises: 9d543c9b12fb
Create Date: 2020-07-27 13:30:13.965062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa9292aa8da2'
down_revision = '9d543c9b12fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_history', sa.Column('title_url', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_history', 'title_url')
    # ### end Alembic commands ###
